export const LANGUAGE_CHOICES = [
    { value: 'python', label: 'Python' },
    { value: 'javascript', label: 'JavaScript' },
    { value: 'typescript', label: 'TypeScript' },
    { value: 'html', label: 'HTML' },
    { value: 'css', label: 'CSS' },
    { value: 'react', label: 'React' },
    { value: 'vue', label: 'Vue' },
    { value: 'angular', label: 'Angular' },
    { value: 'svelte', label: 'Svelte' },
    { value: 'nextjs', label: 'Next.js' },
    { value: 'django', label: 'Django' },
    { value: 'flask', label: 'Flask' },
    { value: 'fastapi', label: 'FastAPI' },
    { value: 'node', label: 'Node.js' },
    { value: 'express', label: 'Express' },
    { value: 'php', label: 'PHP' },
    { value: 'laravel', label: 'Laravel' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'rails', label: 'Ruby on Rails' },
    { value: 'go', label: 'Go' },
    { value: 'rust', label: 'Rust' },
    { value: 'java', label: 'Java' },
    { value: 'spring', label: 'Spring Boot' },
    { value: 'c', label: 'C' },
    { value: 'cpp', label: 'C++' },
    { value: 'csharp', label: 'C#' },
    { value: 'dot-net', label: '.NET' },
    { value: 'swift', label: 'Swift' },
    { value: 'kotlin', label: 'Kotlin' },
    { value: 'dart', label: 'Dart' },
    { value: 'flutter', label: 'Flutter' },
    { value: 'react-native', label: 'React Native' },
    { value: 'sql', label: 'SQL' },
    { value: 'shell', label: 'Shell/Bash' },
    { value: 'unity', label: 'Unity' },
    { value: 'unreal', label: 'Unreal Engine' },
];
